# Generated by Django 2.2.9 on 2020-01-11 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191216_0012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='follows',
            field=models.ManyToManyField(null=True, related_name='followed_by', to='accounts.Profile'),
        ),
    ]
