# Generated by Django 2.2.9 on 2020-01-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_follows'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
