# Generated by Django 3.0 on 2019-12-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_shelf'),
        ('accounts', '0004_auto_20191206_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='book.Book'),
        ),
    ]
