# Generated by Django 3.0 on 2019-12-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191206_0206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='books',
        ),
    ]
