# Generated by Django 3.0 on 2019-12-10 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
