# Generated by Django 3.0 on 2019-12-10 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_profile_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='file',
            new_name='avatar',
        ),
    ]
