# Generated by Django 3.0 on 2019-12-10 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_auto_20191210_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='avatars/default_avatar.png', null=True, upload_to='avatars'),
        ),
    ]
