# Generated by Django 3.0 on 2019-12-10 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20191210_2129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='default/default_avatar.png', upload_to='avatars'),
        ),
    ]
