# Generated by Django 3.0 on 2019-12-11 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_shelf_is_custom'),
        ('accounts', '0018_auto_20191210_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='books',
            field=models.ManyToManyField(related_name='profiles', to='book.BookInfo'),
        ),
    ]
