# Generated by Django 2.2.9 on 2020-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20200103_1848'),
        ('feed', '0004_auto_20200103_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='books',
            field=models.ManyToManyField(null=True, related_name='posts', to='book.ProfileBookInfo'),
        ),
    ]
