# Generated by Django 2.2.9 on 2020-01-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20191224_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilebookinfo',
            name='tags',
            field=models.ManyToManyField(related_name='profile_book', to='book.Tag'),
        ),
    ]
