# Generated by Django 3.0 on 2019-12-06 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_shelf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookInfo',
        ),
    ]
