# Generated by Django 3.0 on 2019-12-06 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_profile_books'),
        ('book', '0003_auto_20191206_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='profile',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shelf', to='accounts.Profile'),
        ),
    ]
