# Generated by Django 3.0 on 2019-12-06 11:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20191206_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookinfo',
            name='authors',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='google_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='pageCount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookinfo',
            name='small_pic_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
