# Generated by Django 3.0 on 2019-12-08 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_auto_20191209_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='shelf',
            name='is_custom',
            field=models.BooleanField(default=True),
        ),
    ]
