# Generated by Django 3.0 on 2019-12-11 22:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_shelf_is_custom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeAdded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_added', to='book.BookInfo')),
            ],
        ),
    ]
