# Generated by Django 3.0 on 2019-12-11 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0011_timeadded_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinfo',
            name='authors',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='bookinfo',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
